/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#aad1742aa6ad90e7140bbed4aac05416c7daa8d1
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _EnterProductionLineDecs, _LeaveProductionLineDecs, _EmitLineDecs, _ExecInstructionLineDecs, _OutputLineDecs, _PunctuatorDecs, _AnyDecs;
import { i, re, spam as m } from '@bablr/boot';
import { CoveredBy, Node, InjectFrom, Literal } from '@bablr/helpers/decorators';
import { o, eat, eatMatch, match } from '@bablr/helpers/grammar';
import * as productions from '@bablr/helpers/productions';
import * as CSTML from '@bablr/language-en-cstml';
import * as Instruction from '@bablr/language-en-bablr-vm-instruction';
import * as Space from '@bablr/language-en-blank-space';
export const dependencies = {
  Space,
  CSTML,
  Instruction
};
export const canonicalURL = 'https://bablr.org/languages/core/en/bablr-cli-verbose-output';
export function* eatMatchTrivia() {
  if (yield match(re`/[ \t\n]/`)) {
    return yield eat(m`#: <*Space:Space />`);
  }
  return null;
}
export const grammar = class VerboseOutputGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Output"], [Node, 2, "ProductionName"], [_EnterProductionLineDecs, 2, "EnterProductionLine"], [_LeaveProductionLineDecs, 2, "LeaveProductionLine"], [_EmitLineDecs, 2, "EmitLine"], [_ExecInstructionLineDecs, 2, "ExecInstructionLine"], [_OutputLineDecs, 2, "OutputLine"], [Node, 2, "Identifier"], [_PunctuatorDecs, 2, "Punctuator"], [_AnyDecs, 2, "Any"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_EnterProductionLineDecs = [CoveredBy('Line'), Node], _LeaveProductionLineDecs = [CoveredBy('Line'), Node], _EmitLineDecs = [CoveredBy('Line'), Node], _ExecInstructionLineDecs = [CoveredBy('Line'), Node], _OutputLineDecs = [CoveredBy('Line'), Node], _PunctuatorDecs = [Literal, Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), "Output")]() {
    while ((yield match(re`/./`)) && (yield eat(m`lines[]: <_Line />`)));
  }
  *Line() {
    yield eat(m`<_Any />`, [m`<ExecInstructionLine /(    )?\>\>\>/ />`, m`<EmitLine '<<<' />`, m`<EnterProductionLine '-->' />`, m`<LeaveProductionLine /[x<]--/ />`, m`<OutputLine />`]);
  }
  *ProductionName() {
    yield eatMatch(m`openBrace: <*Punctuator '[' />`);
    yield eat(m`productionName: <*Identifier />`);
    yield eatMatch(m`closeBrace: <*Punctuator ']' />`);
  }
  *EnterProductionLine() {
    yield eat(m`sigilToken: <*Punctuator '-->' />`);
    yield* eatMatchTrivia();
    yield eat(m`name: <ProductionName />`);
    yield eat(m`lineTerminatorToken: <*Punctuator '\n' />`);
  }
  *LeaveProductionLine() {
    yield eat(m`sigilToken: <*Punctuator /[<x]--/ />`);
    yield* eatMatchTrivia();
    yield eat(m`name: <ProductionName />`);
    yield eat(m`lineTerminatorToken: <*Punctuator '\n' />`);
  }
  *EmitLine() {
    yield eat(m`sigilToken: <*Punctuator '<<<' />`);
    yield* eatMatchTrivia();
    yield eat(m`expression: <CSTML:Tag />`);
    yield eat(m`lineTerminatorToken: <*Punctuator '\n' />`);
  }
  *ExecInstructionLine() {
    yield eatMatch(m`#: <*Space:Space /[ \t]+/ />`);
    yield eat(m`sigilToken: <*Punctuator '>>>' />`);
    yield* eatMatchTrivia();
    yield eat(m`instruction: <Instruction:Call />`);
    yield eat(m`lineTerminatorToken: <*Punctuator '\n' />`);
  }
  *OutputLine() {
    yield* eatMatchTrivia();
    // yield i`eat(m'expressions[]: <CSTML:Tag />')`;
    yield eat(m`expressions[]: <CSTML:Tag />`);
    yield eatMatch(m`#: <*Space:Space /[ \t]/ />`);
    while (yield eatMatch(m`expressions[]: <CSTML:Tag />`)) {
      yield eatMatch(m`#: <*Space:Space /[ \t]/ />`);
    }
    yield eat(m`lineTerminatorToken: <*Punctuator '\n' />`);
  }
  *Identifier() {
    yield eat(re`/[a-zA-Z]+/`);
  }
  *Punctuator() {}
  *Any() {}
};