/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#fcb1b34cdc5736146db3102a3dfd94277a9127eb
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
let _initProto, _EnterProductionLineDecs, _LeaveProductionLineDecs, _EmitLineDecs, _ExecInstructionLineDecs, _OutputLineDecs, _PunctuatorDecs, _AnyDecs;
import { i } from '@bablr/boot';
import { CoveredBy, Node, InjectFrom } from '@bablr/helpers/decorators';
import * as productions from '@bablr/helpers/productions';
import * as CSTML from '@bablr/language-en-cstml';
import * as Instruction from '@bablr/language-en-bablr-vm-instruction';
import * as Space from '@bablr/language-en-blank-space';
export const dependencies = {
  Space,
  CSTML,
  Instruction
};
export const canonicalURL = 'https://bablr.org/languages/core/en/bablr-cli-verbose-output';
export function* eatMatchTrivia() {
  if (yield i`match(/[ \t\n]/)`) {
    return yield i`eat(#: <*Space:Space />)`;
  }
  return null;
}
export const grammar = class VerboseOutputGrammar {
  static {
    [_initProto] = _applyDecs(this, [[Node, 2, "Output"], [Node, 2, "ProductionName"], [_EnterProductionLineDecs, 2, "EnterProductionLine"], [_LeaveProductionLineDecs, 2, "LeaveProductionLine"], [_EmitLineDecs, 2, "EmitLine"], [_ExecInstructionLineDecs, 2, "ExecInstructionLine"], [_OutputLineDecs, 2, "OutputLine"], [Node, 2, "Identifier"], [_PunctuatorDecs, 2, "Punctuator"], [_AnyDecs, 2, "Any"]], []).e;
  }
  constructor() {
    _initProto(this);
  }
  *[(_EnterProductionLineDecs = [CoveredBy('Line'), Node], _LeaveProductionLineDecs = [CoveredBy('Line'), Node], _EmitLineDecs = [CoveredBy('Line'), Node], _ExecInstructionLineDecs = [CoveredBy('Line'), Node], _OutputLineDecs = [CoveredBy('Line'), Node], _PunctuatorDecs = [Node, InjectFrom(productions)], _AnyDecs = InjectFrom(productions), "Output")]() {
    while ((yield i`match(/./)`) && (yield i`eat(lines[]: <Line />)`));
  }
  *Line() {
    yield i`eat(<Any /> [
      <ExecInstructionLine /(    )?\>\>\>/ />
      <EmitLine '<<<' />
      <EnterProductionLine '-->' />
      <LeaveProductionLine /[x<]--/ />
      <OutputLine />
    ])`;
  }
  *ProductionName() {
    yield i`eatMatch(openBrace: <*Punctuator '[' />)`;
    yield i`eat(productionName: <*Identifier />)`;
    yield i`eatMatch(closeBrace: <*Punctuator ']' />)`;
  }
  *EnterProductionLine() {
    yield i`eat(sigilToken: <*Punctuator '-->' />)`;
    yield* eatMatchTrivia();
    yield i`eat(<ProductionName />)`;
    yield i`eat(lineTerminatorToken: <*Punctuator '\n' />)`;
  }
  *LeaveProductionLine() {
    yield i`eat(sigilToken: <*Punctuator /[<x]--/ />)`;
    yield* eatMatchTrivia();
    yield i`eat(<ProductionName />)`;
    yield i`eat(lineTerminatorToken: <*Punctuator '\n' />)`;
  }
  *EmitLine() {
    yield i`eat(sigilToken: <*Punctuator '<<<' />)`;
    yield* eatMatchTrivia();
    yield i`eat(expression: <CSTML:Tag />)`;
    yield i`eat(lineTerminatorToken: <*Punctuator '\n' />)`;
  }
  *ExecInstructionLine() {
    yield i`eatMatch(#: <*Space:Space /[ \t]+/ />)`;
    yield i`eat(sigilToken: <*Punctuator '>>>' />)`;
    yield* eatMatchTrivia();
    yield i`eat(instruction: <Instruction:Call />)`;
    yield i`eat(lineTerminatorToken: <*Punctuator '\n' />)`;
  }
  *OutputLine() {
    yield* eatMatchTrivia();
    yield i`eat(expressions[]: <CSTML:Tag />)`;
    yield i`eatMatch(#: <*Space:Space /[ \t]/ />)`;
    while (yield i`eatMatch(expressions[]: <CSTML:Tag />)`) {
      yield i`eatMatch(#: <*Space:Space /[ \t]/ />)`;
    }
    yield i`eat(lineTerminatorToken: <*Punctuator '\n' />)`;
  }
  *Identifier() {
    yield i`eat(/[a-zA-Z]+/)`;
  }
  *Punctuator() {}
  *Any() {}
};